---
title: "w1qz.Rmd"
output: 
        html_document:
                toc: true
                toc_float: true
                number_sections: false
                theme: darkly
---
# About

This file documents the process answering Week 1 quiz. 

Abbreviations: 
        - Ans = Answer 
        

# Q1 Which of the following is a principle of analytic graphics?

Ans: Integrate multiple modes of evidence

# Q2 What is the role of exploratory graphs in data analysis?

Ans They are typically made very quickly.

# Q3 Which of the following is true about the base plotting system?

Ans: Plots are created and annotated with separate functions

# Q4 Which of the following is an example of a valid graphics device in R?

A PDF file

# Q5 Which of the following is an example of a vector graphics device in R?

Ans: SVG

# Q6 Bitmapped file formats can be most useful for

Ans: Scatterplots with many many points

# Q7 Which of the following functions is typically used to add elements to a plot in the base graphics system?

Ans: text()

# Q8 Which function opens the screen graphics device for the Mac?

Ans: quartz()

# Q9 What does the 'pch' option to par() control?

Ans: the plotting symbol/character in the base graphics system

# Q10 If I want to save a plot to a PDF file, which of the following is a correct way of doing that?

Ans: Construct the plot on the screen device and then copy it to a PDF file with dev.copy2pdf()
