---
title: "q1-regmo"
author: "Tanya Tan"
date: "11/10/2019"
output: html_document
---
# Staus

done but not submitted 

#Q1
```{r}
x <- c(0.18, -1.54, 0.42, 0.95)
w <- c(2, 1, 3, 1)
sum(x*w)/sum(w)

```

#Q2 
```{r}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)

lm(y~0+x)
```

#Q3
```{r}
data(mtcars)
summary(lm(mpg~wt,data=mtcars))
```

#Q4 
```{r}
sdx_div_y<-0.5
corr<-0.5
beta<-corr/sdx_div_y
beta
```


#Q5

```{r}
#quiz 1 is x and quiz 2 is y 
#quiz 1 score is 1.5
#cor(x,y)=0.4
#quiz 2 score=quiz1-score*cor(y,x)
1.5*0.4
```



#Q6

```{r}
x <- c(8.58, 10.46, 9.01, 9.64, 8.86)
(x[1]-mean(x))/sd(x)
```


#Q7 

```{r}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
y <- c(1.39, 0.72, 1.55, 0.48, 1.19, -1.59, 1.23, -0.65, 1.49, 0.05)

summary(lm(y~x))
```


#Q9

```{r}
x <- c(0.8, 0.47, 0.51, 0.73, 0.36, 0.58, 0.57, 0.85, 0.44, 0.42)
mean(x)
```

#Q10

```{r}

```





